#!/bin/bash

PATH_PRIVATE_DATA="/root/private_data"


if [ ! -f $PATH_PRIVATE_DATA ]; then
	command "touch $PATH_PRIVATE_DATA"
	command "chmod 600 $PATH_PRIVATE_DATA"
fi

source $PATH_PRIVATE_DATA

function set_private_data() {
	key=$1
	value=$2

	# Check if the key already exists
	if grep -q $key $PATH_PRIVATE_DATA; then
		# Replace the value of the key
		sed -i "s/$key=.*/$key=$value/" $PATH_PRIVATE_DATA
	else
		# Add the key and value
		echo "$key=$value" >> $PATH_PRIVATE_DATA
	fi
}


function check_private_data() {
	key=$1

	# Check if the key exists
	if grep -q $key $PATH_PRIVATE_DATA; then
		echo "true"
	else
		echo "false"
	fi
}


