#!/bin/bash
#
# 
#  _____        _
# |~>   |     ('v') 
# /:::::\    /{w w}\ 
#--------------------------------
# Copyright Florian Orzol
#
# description: this script creates a bootable USB stick with Proxmox VE
# date: 2024-10-18
# version: 1.0 
#
#    <')
# \_;( )
# >>>> START SCRIPT <<<< #
#
#


dirRoot=$(dirname $(readlink -f $0))
source $dirRoot/support_functions
source $dirRoot/private_data

PN="serma"

# check if symlink exists
if [ ! -f /usr/bin/serma ]; then
	information "Create symlink to /usr/bin"
	command "ln -s $dirRoot/$PN /usr/bin/$PN"
fi

echo "debug: 1: $1"
# if $1 is empty, show options

if [  -z $1 ]; then
	information "Available options:"
	# list all files in libs directory
	ls $dirRoot/libs
	exit
fi


echo "debug: 2: $1"
echo "debug: 3: $2"

source $dirRoot/libs/$1
if [ -z $2 ]; then
	tasks $2
else
	tasks 
fi
