#!/bin/bash
#
# 
#  _____        _
# |~>   |     ('v') 
# /:::::\    /{w w}\ 
#--------------------------------
# Copyright Florian Orzol
#
# description: this script updates scripts from git-repo
# date: 2024-10-21
# version: 1.0 
#
#    <')
# \_;( )
# >>>> START SCRIPT <<<< #
#

function check_git_repo() {
	if [ -f $GIT_REPO ]; then
		real_tasks git-connection
	fi
}
	


function real_tasks() {
	task=$1

	#currentPath="$(pwd)"
	case $task in
		"git-connection")
			section "Enter git-repo credentials"

			# enter git-repo url until it is valid
			while true; do
				GIT_REPO=$(enter "Please enter git-repo url: ") 
				command "git ls-remote $GIT_REPO"
				if [ $? -ne 0 ]; then
					warning "Please enter a valid git-repo url"
				else
					break
				fi
			done
			# set git-repo url as private data
			information "Set GIT_REPO in $PATH_PRIVATE_DATA"
			set_private_data "GIT_REPO" $GIT_REPO
			;;
		"update")
			section "Update scripts from git-repo"
			# update scripts with user data from private_data file to dirRoot
			command "cd $dirRoot"
			command "git pull"
			;;
		*)
			echo "No task found"
;;
	esac

	#command "cd $currentPath"
			
}

function tasks() {
	task=$1

	check_git_repo $task
	real_tasks $task
}
