#!/bin/bash
#
# 
#  _____        _
# |~>   |     ('v') 
# /:::::\    /{w w}\ 
#--------------------------------
# Copyright Florian Orzol
#
# description: this script updates scripts from git-repo
# date: 2024-10-21
# version: 1.0 
#
#    <')
# \_;( )
# >>>> START SCRIPT <<<< #
#

if [ -f $GIT_REPO ]; then
	section "Enter git-repo credentials"

	# enter git-repo url until it is valid
	while true; do
		GIT_REPO=$(enter "Please enter git-repo url: ") 
		command "git ls-remote $GIT_REPO"
		if [ $? -ne 0 ]; then
			warning "Please enter a valid git-repo url"
		else
			break
		fi
	done
	# set git-repo url as private data
	information "Set GIT_REPO in $PATH_PRIVATE_DATA"
	set_private_data "GIT_REPO" $GIT_REPO
	;;
fi
	


function tasks() {
	local task=$1

	#currentPath="$(pwd)"
	case $task in
		"update")
			section "Update scripts from git-repo"
			# update scripts with user data from private_data file to dirRoot
			command "cd $dirRoot"
			command "git pull"
			;;
		*)
			echo "No task found"
			;;
	esac

	#command "cd $currentPath"
			
}

