#!/bin/bash
#
# 
#  _____        _
# |~>   |     ('v') 
# /:::::\    /{w w}\ 
#--------------------------------
# Copyright Florian Orzol
#
# description: setup Proxmox VE
# date: 2024-10-21
# version: 1.0 
#
#    <')
# \_;( )
# >>>> START SCRIPT <<<< #
#


function test() {

	debug "source $dirRoot/libs/system\ntasks show-snapshots"
	source $dirRoot/libs/system
	tasks "show-snapshots"

}

function test1() {
	debug ".$dirRoot/libs/system tasks show-snapshots"
	$dirRoot/libs/system tasks show-snapshots
}

function test2() {
	debug "serma system show-snapshots"
	serma system show-snapshots
}



function tasks() {
	task=$1
	tasks=("test" "test1" "test2")
	case $task in
		"test")
			test
			;;
		"test1")
			test1
			;;
		"test2")
			test2
			;;
		*)
			information "Available tasks:\n${tasks[@]}"
			;;
	esac
}
