#!/bin/bash
#
# 
#  _____        _
# |~>   |     ('v') 
# /:::::\    /{w w}\ 
#--------------------------------
# Copyright Florian Orzol
#
# description: setup Proxmox VE
# date: 2024-10-21
# version: 1.0 
#
#    <')
# \_;( )
# >>>> START SCRIPT <<<< #
#


function ceph() {
	section "Install Ceph"

	debug "try to call system show_snapshots"
	source $dirRoot/libs/system
	tasks show_snapshots
}



function tasks() {
	task=$1
	tasks=("ceph")
	case $task in
		"ceph")
			ceph
			;;
		*)
			information "Available tasks:\n${tasks[@]}"
			;;
	esac
}
